config/routes.rb
Rails.application.routes.draw do
  resources :bus_lines

  resources :directions

  resources :bus_stops

  resources :departures

  resources :users

  resources :sessions

  root to: "bus_lines#index"

end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  before_action :set_line, only: [:show, :edit, :update, :destroy]
  before_action :user_must_be_logged_in!, except: [:index, :show]

  # GET /lines
  # GET /lines.json
  def index
    @lines = Line.all.order(:name)
  end

  # GET /lines/1
  # GET /lines/1.json
  def show
  end

  # GET /lines/new
  def new
    @line = Line.new
  end

  # GET /lines/1/edit
  def edit
  end

  # POST /lines
  # POST /lines.json
  def create
    @line = Line.new(line_params)

    respond_to do |format|
      if @line.save
        format.html { redirect_to @line, notice: 'Line was successfully created.' }
        format.json { render :show, status: :created, location: @line }
      else
        format.html { render :new }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lines/1
  # PATCH/PUT /lines/1.json
  def update
    respond_to do |format|
      if @line.update(line_params)
        format.html { redirect_to @line, notice: 'Line was successfully updated.' }
        format.json { render :show, status: :ok, location: @line }
      else
        format.html { render :edit }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lines/1
  # DELETE /lines/1.json
  def destroy
    @line.destroy
    respond_to do |format|
      format.html { redirect_to lines_url, notice: 'Line was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line
      @line = Line.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_params
      params.require(:line).permit(:name)
    end
end

app/views/lines/_form.html.erb
<div class="row">
  <div class="col-lg-2 col-md-4">
    <%= form_for(@line) do |f| %>
      <% if @line.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@line.errors.count, "error") %> prohibited this line from being saved:</h2>

          <ul>
          <% @line.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="actions">
        <%= f.submit nil, class: "btn btn-default" %>
      </div>
    <% end %>
  </div>
</div>

app/views/lines/edit.html.erb
<div class="row">
  <div class="col-lg-12 col-md-12">
    <h1>Editing line</h1>
  </div>
</div>

<%= render 'form' %>

<div class="row">
  <div class="col-lg-12 col-md-12">
		<%= link_to 'Show', @line %> |
		<%= link_to 'Back', lines_path %>
  </div>
</div>

app/views/lines/index.html.erb
<div class="row">
  <div class="col-md-4">
    <h1>Regensburg</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <ol class="breadcrumb">
      <li class="active">Buslinien</li>
    </ol>
  </div>
</div>

<% if logged_in? %>

  <div class="row">
    <div class="col-md-4">
      <ul class="list-group">
        <% @lines.each do |line| %>
          <li class="list-group-item">
            <%= link_to "#{line.name}", line %> / 
            <%= link_to 'Edit', edit_line_path(line) %> / 
            <%= link_to 'Destroy', line, method: :delete, data: { confirm: 'Are you sure?' } %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <%= link_to 'Linie hinzufügen', new_line_path, class: "btn btn-link" %>
    </div>
  </div>

<% else %>
  <div class="row">
    <div class="col-md-4">
      <div class="list-group">
        <% @lines.each do |line| %>
            <%= link_to "#{line.name}", line, class: "list-group-item" %>
        <% end %>
      </div>
    </div>
  </div>
  
<% end %>

app/views/lines/new.html.erb
<div class="row">
  <div class="col-lg-12 col-md-12">
    <h1>New line</h1>
  </div>
</div>

<%= render 'form' %>

app/views/lines/show.html.erb
<div class="row">
  <div class="col-md-4">
    <h1>Regensburg</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <ol class="breadcrumb">
      <li><%= link_to 'Buslinien', lines_path %></li>
      <li class="active"><%= @line.name %></li>
    </ol>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <p>
      Richtung:
    </p>
  </div>
</div>

<% if logged_in? %>
  <div class="row">
    <div class="col-md-4">
      <ul class="list-group">
        <% @line.directions.each do |direction| %>
          <li class="list-group-item">
            <%= link_to direction.display_name, direction %> / 
            <%= link_to 'Edit', edit_direction_path(direction) %> / 
            <%= link_to 'Destroy', direction, method: :delete, data: { confirm: 'Are you sure?' } %>
          </li>  
        <% end %>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <%= link_to 'Richtung hinzufügen', new_direction_path, class: "btn btn-link" %>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-4">
      <div class="list-group">
        <% @line.directions.each do |direction| %>
          <%= link_to direction.display_name, direction, class: "list-group-item" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>