config/routes.rb
Rails.application.routes.draw do
  resources :bus_lines

  resources :directions

  resources :bus_stops

  resources :departures

  resources :users

  resources :sessions

  root to: "bus_lines#index"

end

app/models/bus_line.rb
class BusLine < ActiveRecord::Base
	has_many :directions

  scope :active, -> { where("active = ?", 1) }
end

app/controllers/bus_lines_controller.rb
class BusLinesController < ApplicationController
  before_action :set_line, only: [:show, :edit, :update, :destroy]
  before_action :user_must_be_logged_in!, except: [:index, :show]

  # GET /lines
  # GET /lines.json
  def index
    @bus_lines = BusLine.active.order(:name)
  end

  # GET /lines/1
  # GET /lines/1.json
  def show
  end

  # GET /lines/new
  def new
    @bus_line = BusLine.new
  end

  # GET /lines/1/edit
  def edit
  end

  # POST /lines
  # POST /lines.json
  def create
    @bus_line = BusLine.new(line_params)

    respond_to do |format|
      if @bus_line.save
        format.html { redirect_to @bus_line, notice: 'BusLine was successfully created.' }
        format.json { render :show, status: :created, location: @bus_line }
      else
        format.html { render :new }
        format.json { render json: @bus_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lines/1
  # PATCH/PUT /lines/1.json
  def update
    respond_to do |format|
      if @bus_line.update(line_params)
        format.html { redirect_to @bus_line, notice: 'BusLine was successfully updated.' }
        format.json { render :show, status: :ok, location: @bus_line }
      else
        format.html { render :edit }
        format.json { render json: @bus_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lines/1
  # DELETE /lines/1.json
  def destroy
    @bus_line.destroy
    respond_to do |format|
      format.html { redirect_to lines_url, notice: 'BusLine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line
      @bus_line = BusLine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_params
      params.require(:bus_line).permit(:name)
    end
end

app/helpers/bus_lines_helper.rb
module BusLinesHelper
end

app/views/bus_lines/_form.html.erb
<%= form_for(@bus_line) do |f| %>
  <% if @bus_line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bus_line.errors.count, "error") %> prohibited this line from being saved:</h2>

      <ul>
      <% @bus_line.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit nil, class: "btn btn-default" %>
  </div>
<% end %>

app/views/bus_lines/edit.html.erb
<div class="row">
  <div class="col-lg-12 col-md-12">
    <h1>Editing line</h1>
  </div>
</div>

<%= render 'form' %>

<div class="row">
  <div class="col-lg-12 col-md-12">
		<%= link_to 'Show', @bus_line %> |
		<%= link_to 'Back', bus_lines_path %>
  </div>
</div>

app/views/bus_lines/index.html.erb
<ol class="breadcrumb">
  <li class="active">Buslinien</li>
</ol>

<h1>Regensburg</h1>
<h4>Welchen Bus möchtest Du nehmen?</h4>

<% if logged_in? %>

  <ul class="list-group">
    <% @bus_lines.each do |line| %>
      <li class="list-group-item">
        <%= link_to "#{line.name}", line %> / 
        <%= link_to 'Edit', edit_bus_line_path(line) %> / 
        <%= link_to 'Destroy', line, method: :delete, data: { confirm: 'Are you sure?' } %>
      </li>
    <% end %>
  </ul>
  <%= link_to 'Buslinie hinzufügen', new_bus_line_path, class: "btn btn-link" %>

<% else %>
  
  <div class="list-group">
    <% @bus_lines.each do |line| %>
        <%= link_to "#{line.name}", line, class: "list-group-item" %>
    <% end %>
  </div>

<% end %>

app/views/bus_lines/new.html.erb
<h1>New bus line</h1>

<%= render 'form' %>

app/views/bus_lines/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Buslinien', bus_lines_path %></li>
  <li class="active"><%= @bus_line.name %></li>
</ol>

<h1>Regensburg</h1>
<h4>In welche Richtung möchtest Du fahren?</h4>

<% if logged_in? %>

  <ul class="list-group">
    <% @bus_line.directions.each do |direction| %>
      <li class="list-group-item">
        <%= link_to direction.display_name, direction %> / 
        <%= link_to 'Edit', edit_direction_path(direction) %> / 
        <%= link_to 'Destroy', direction, method: :delete, data: { confirm: 'Are you sure?' } %>
      </li>  
    <% end %>
  </ul>
  <%= link_to 'Richtung hinzufügen', new_direction_path, class: "btn btn-link" %>

<% else %>

  <div class="list-group">
    <% @bus_line.directions.each do |direction| %>
      <%= link_to direction.display_name, direction, class: "list-group-item" %>
    <% end %>
  </div>
 
<% end %>