config/routes.rb
Rails.application.routes.draw do
  resources :bus_lines

  resources :directions

  resources :bus_stops

  resources :departures

  resources :users

  resources :sessions

  root to: "bus_lines#index"

end

app/models/direction.rb
class Direction < ActiveRecord::Base
  belongs_to :bus_line
  has_many :bus_stops
end

app/controllers/directions_controller.rb
class DirectionsController < ApplicationController
  before_action :set_direction, only: [:show, :edit, :update, :destroy]
  before_action :user_must_be_logged_in!, except: [:show]

  # GET /directions
  # GET /directions.json
  def index
    @directions = Direction.all
  end

  # GET /directions/1
  # GET /directions/1.json
  def show
    #expires_now()
  end

  # GET /directions/new
  def new
    @direction = Direction.new
  end

  # GET /directions/1/edit
  def edit
  end

  # POST /directions
  # POST /directions.json
  def create
    @direction = Direction.new(direction_params)

    respond_to do |format|
      if @direction.save
        format.html { redirect_to @direction, notice: 'Direction was successfully created.' }
        format.json { render :show, status: :created, location: @direction }
      else
        format.html { render :new }
        format.json { render json: @direction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /directions/1
  # PATCH/PUT /directions/1.json
  def update
    respond_to do |format|
      if @direction.update(direction_params)
        format.html { redirect_to @direction, notice: 'Direction was successfully updated.' }
        format.json { render :show, status: :ok, location: @direction }
      else
        format.html { render :edit }
        format.json { render json: @direction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directions/1
  # DELETE /directions/1.json
  def destroy
    @direction.destroy
    respond_to do |format|
      format.html { redirect_to directions_url, notice: 'Direction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_direction
      @direction = Direction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def direction_params
      params.require(:direction).permit(:display_name, :search_name, :bus_line_id)
    end
end

app/helpers/directions_helper.rb
module DirectionsHelper
end

app/views/directions/_form.html.erb
<%= form_for(@direction) do |f| %>

  <% if @direction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@direction.errors.count, "error") %> prohibited this direction from being saved:</h2>

      <ul>
      <% @direction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :display_name %>
    <%= f.text_field :display_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :search_name %>
    <%= f.text_field :search_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :bus_line_id %>
    <%= f.select(:bus_line_id, options_from_collection_for_select(BusLine.all, "id", "name"), {}, {class: "form-control"}) %>
  </div>
  <div class="actions">
    <%= f.submit nil, class: "btn btn-default" %>
  </div>
<% end %>

app/views/directions/edit.html.erb
<h1>Editing direction</h1>

<%= render 'form' %>

<%= link_to 'Show', @direction %> |
<%= link_to 'Back', directions_path %>

app/views/directions/index.html.erb
<h1>Listing directions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Line</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @directions.each do |direction| %>
      <tr>
        <td><%= direction.display_name %></td>
        <td><%= direction.line.name %></td>
        <td><%= link_to 'Show', direction %></td>
        <td><%= link_to 'Edit', edit_direction_path(direction) %></td>
        <td><%= link_to 'Destroy', direction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Direction', new_direction_path %>

app/views/directions/new.html.erb
<div class="row">
  <div class="col-lg-12 col-md-12">
    <h1>New direction</h1>
  </div>
</div>

<%= render 'form' %>

app/views/directions/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Buslinien', bus_lines_path %></li>
  <li><%= link_to @direction.bus_line.name, bus_line_path(@direction.bus_line) %></li>
  <li class="active"><%= @direction.display_name %></li>
</ol>

<h1>Regensburg</h1>
<h4>An welcher Haltestelle möchtest Du einsteigen?</h4>

<% if logged_in? %>

  <ul class="list-group">
    <% @direction.bus_stops.each do |bus_stop| %>
      <li class="list-group-item">
        <!-- Show a loading indicator-->
        <%= link_to bus_stop.display_name, bus_stop, {class: "list-group-item", :onclick => "$('#loadingAnimation').modal({backdrop: 'static', keyboard: false});"} %>
        <%= link_to 'Edit', edit_bus_stop_path(bus_stop) %> / 
        <%= link_to 'Destroy', bus_stop, method: :delete, data: { confirm: 'Are you sure?' } %>
      </li>
    <% end %>
  </ul>
  <%= link_to 'Haltestelle hinzufügen', new_bus_stop_path, class: "btn btn-link" %>

<% else %>

  <div class="list-group">
    <% @direction.bus_stops.each do |bus_stop| %>
      <!-- Show a loading indicator-->
      <%= link_to bus_stop.display_name, bus_stop, {class: "list-group-item", :onclick => "$('#loadingAnimation').modal({backdrop: 'static', keyboard: false});"} %>
    <% end %>
  </div>

<% end %>

<!-- Modal -->
<div class="modal fade" id="loadingAnimation" tabindex="-1" role="dialog" aria-labelledby="loadingAnimationLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h4 class="modal-title" id="loadingAnimationLabel">Abfrage läuft...</h4>
      </div>

      <div class="modal-body">
        <div class="progress">
          <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
            
          </div>
        </div>
      </div>
      
    </div>
  </div>
</div>