config/routes.rb
Rails.application.routes.draw do
  resources :bus_lines

  resources :directions

  resources :bus_stops

  resources :departures

  resources :users

  resources :sessions

  root to: "bus_lines#index"

end

app/models/bus_stop.rb
class BusStop < ActiveRecord::Base
  belongs_to :direction
  has_many :departures
end

app/controllers/bus_stops_controller.rb
require 'capybara/poltergeist'

class BusStopsController < ApplicationController
  before_action :set_bus_stop, only: [:show, :edit, :update, :destroy]
  before_action :user_must_be_logged_in!, except: [:show]

  # GET /bus_stops
  # GET /bus_stops.json
  def index
    @bus_stops = BusStop.all
  end

  # GET /bus_stops/1
  # GET /bus_stops/1.json
  def show
    # Aufberteitung der Abfahrtszeiten für das jquery countdown plugin
    # Format: @departures = ['2015/03/19 22:42:30', '2015/03/19 22:44:00']
    @departures = []
    t = Time.new
    date_part = t.strftime("%Y/%m/%d")
    cur_hour = t.hour
    cur_min = t.min

    # Call method like this:
    # p_direction = "Regensburg Schwabenstraße"
    # p_bust_stop = "Regensburg, Karl-Stieler-Straße"
    @time_only_departures = search(@bus_stop.direction.search_name, @bus_stop.search_name)

    @date_and_time_departures = format_departure_values(@time_only_departures, date_part)
  end

  def format_departure_values(dps, date_part)
    result = Array.new
    dps.each do |d|
      # Add the current date, hours and minutes should alway have two digits
      tmp = sprintf("%s %02d:%02d:00", date_part, d.hour, d.minute)
      logger.info "Formatted deparute time (with date): #{tmp}"
      result << tmp
    end
    return result
  end

  def search(p_direction, p_bus_stop)
    logger.info "Starting query on bayern-fahrplan.de with:"
    logger.info "Direction: #{p_direction}"
    logger.info "Bus Stop: #{p_bus_stop}"
    # ========Set up begin====================================
    options = {js_errors: false}
    Capybara.register_driver :poltergeist do |app|
      Capybara::Poltergeist::Driver.new(app, options)
    end
    Capybara.default_driver = :poltergeist
    Capybara.javascript_driver = :poltergeist

    internet = Capybara.current_session
    internet.class # => Capybara::Session
    # =========================================================

    # ============Page specific data=========================
    url  = "http://www.bayern-fahrplan.de/de/abfahrt-ankunft"
    # ========================================================

    internet.visit(url)
    # Query departures for the given bus stop
    internet.click_link('Haltestelle')
    internet.fill_in('name_dm', with: p_bus_stop)
    
    internet.click_button("search")

    # Show only departures with the right direction
    internet.click_link('Anzeige-Filter')
    # Deselect everything
    internet.find(:xpath, '//a[@class = "checknone"]').click
    # Select transportation type 'Regionalbus'
    internet.find(:xpath, '//label[text() = "Stadtbus"]').click
    internet.find(:xpath, '//label[text() = "Regionalbus"]').click
    # Select the right direction
    xpath = "//label[contains(., '%s')]" % p_direction
    id = internet.first(:xpath, xpath)['for']
    xpath = "//label[@for='%s']" % id
    internet.first(:xpath, xpath).click
    
    # Apply filter
    internet.click_button('save1')

    # The browser needs some time to apply the filter
    sleep(1)
    
    xpath_value = "//table[@class='trip']/tbody/tr/td[1]"

    found_departures = []
    internet.all(:xpath, xpath_value).each { |td|
      logger.info "Candidate for departure: #{td.text}"
      if match = td.text.match(/^(\d{2,2}):(\d{2,2}).*$/)
        logger.info "Accepted candidate: #{td.text}"
        d = Departure.new
        d.bus_stop_id = @bus_stop.id
        d.hour = match[1].strip.to_i
        d.minute = match[2].strip.to_i
        found_departures << d
      end
    }
    logger.info "Anzahl gefundener Abfahrtszeiten: #{found_departures.size()}"
    return found_departures;
  end

  # GET /bus_stops/new
  def new
    @bus_stop = BusStop.new
  end

  # GET /bus_stops/1/edit
  def edit
  end

  # POST /bus_stops
  # POST /bus_stops.json
  def create
    @bus_stop = BusStop.new(bus_stop_params)

    respond_to do |format|
      if @bus_stop.save
        format.html { redirect_to @bus_stop, notice: 'Bus stop was successfully created.' }
        format.json { render :show, status: :created, location: @bus_stop }
      else
        format.html { render :new }
        format.json { render json: @bus_stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bus_stops/1
  # PATCH/PUT /bus_stops/1.json
  def update
    respond_to do |format|
      if @bus_stop.update(bus_stop_params)
        format.html { redirect_to @bus_stop, notice: 'Bus stop was successfully updated.' }
        format.json { render :show, status: :ok, location: @bus_stop }
      else
        format.html { render :edit }
        format.json { render json: @bus_stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bus_stops/1
  # DELETE /bus_stops/1.json
  def destroy
    @bus_stop.destroy
    respond_to do |format|
      format.html { redirect_to bus_stops_url, notice: 'Bus stop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bus_stop
      @bus_stop = BusStop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bus_stop_params
      params.require(:bus_stop).permit(:display_name, :search_name, :direction_id)
    end
end

app/helpers/bus_stops_helper.rb
module BusStopsHelper

end

app/views/bus_stops/_form.html.erb
<div class="row">
  <div class="col-lg-2 col-md-4">

    <%= form_for(@bus_stop) do |f| %>
      <% if @bus_stop.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@bus_stop.errors.count, "error") %> prohibited this bus_stop from being saved:</h2>
          <ul>
            <% @bus_stop.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :display_name %>
        <%= f.text_field :display_name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :search_name %>
        <%= f.text_field :search_name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :direction_id %>
        <%= f.select(:direction_id, options_from_collection_for_select(Direction.all, "id", "display_name"), {}, {class: "form-control"}) %>
      </div>
      <div class="actions">
        <%= f.submit nil, class: "btn btn-default"%>
      </div>
    <% end %>

  </div>
</div>

app/views/bus_stops/edit.html.erb
<h1>Editing bus_stop</h1>

<%= render 'form' %>

app/views/bus_stops/index.html.erb
<h1>Listing bus_stops</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Direction</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bus_stops.each do |bus_stop| %>
      <tr>
        <td><%= bus_stop.display_name %></td>
        <td><%= bus_stop.direction.display_name %></td>
        <td><%= link_to 'Show', bus_stop %></td>
        <td><%= link_to 'Edit', edit_bus_stop_path(bus_stop) %></td>
        <td><%= link_to 'Destroy', bus_stop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bus stop', new_bus_stop_path %>

app/views/bus_stops/new.html.erb
<div class="row">
  <div class="col-lg-12 col-md-12">
    <h1>New bus_stop</h1>
  </div>
</div>

<%= render 'form' %>

app/views/bus_stops/show.html.erb
<ol class="breadcrumb" style="margin-bottom:0px">
  <li><%= link_to 'Buslinien', bus_lines_path %></li>
  <li><%= link_to @bus_stop.direction.bus_line.name, bus_line_path(@bus_stop.direction.bus_line) %></li>
  <li><%= link_to 'Richtung ' + @bus_stop.direction.display_name, direction_path(@bus_stop.direction) %></li>
  <!--<li class="active"><%= @bus_stop.display_name %></li>-->
</ol>
<h1>Regensburg</h1>

<%= javascript_tag do %>
  window.departures = <%= raw @date_and_time_departures.to_json %>;
<% end %>

<h3><span class="label label-warning">Haltestelle: <%= @bus_stop.display_name %></span></h3>

<h3>
  <span class="label label-success">Abfahrt in:
    <!-- Count Down Element-->
    <span id="clock"></span>
  </span>
  <script type="text/javascript">
    $('span#clock').countdown(departures.shift())
      .on('update.countdown', function(event) {
        $(this).html(event.strftime('%H:%M:%S'));
      })
      .on('finish.countdown', function(event) {
        console.log('Timer expired');
        if (departures.length > 0) {
          console.log('Resetting...');
          $('span#clock').countdown(departures.shift());
        }
      });
  </script>
</h3>
    
<table class="table table-bordered">
  <thead>
    <tr>
      <th>
          Abfahrtszeiten:
      </th>
    </tr>
  </thead>
  <tbody class="marker">
      <% @time_only_departures.each do |element| %>
        <tr>
          <td><%= sprintf("%02d:%02d", element.hour, element.minute) %></td>
        </tr>
      <% end %>
  </tbody>
</table>